version: '3.1'
services:
    coredns:
        image: coredns/coredns
        container_name: coredns
        command: -conf /etc/coredns/Corefile
        restart: on-failure # other option: always - if you want persistent through host reboots
        expose:
            - '53'
            - '53/udp'
            - '9153'
        ports:
            - '53:53'
            - '53:53/udp'
            - '9153:9153'
        volumes:
            - './config:/etc/coredns'

    prometheus:
        image: prom/prometheus
        restart: on-failure
        expose:
            - '9090'
        ports:
            - '9090:9090'
        volumes:
            - './prometheus/prometheus.yml:/etc/prometheus/prometheus.yml'

    grafana:
        image: grafana/grafana-enterprise
        container_name: grafana
        restart: unless-stopped
        ports:
        - '3000:3000'